// Backpack records, in catalog order. `location` is "EditorID — readable place".
// cc and dr list the base value first and the best upgrade last; `upgrades` summarises the tiers.
const BACKPACKS = [
  {
    num: 1, level: 1,
    name: "Small Shoulder Bag",
    id: "BPShoulder",
    desc: "Increases the wearer's overall carry capacity by +10.",
    location: "RedRocketCaveExt — Inside house southeast of Red Rocket Truck Stop",
    cc: "+10 / +15 / +20 CC",
    dr: "+2 DR",
    special: [],
    crafting: "Adhesive ×3 · Leather ×3 · Wonderglue ×1 · Cloth ×6",
    weight: "1 lbs",
    value: "59 caps",
    colors: ["Default"],
    upgrades: ["+10 CC Base", "+15 CC Reinforced", "+20 CC Heavy Duty"]
  },
  {
    num: 2, level: 5,
    name: "Postman's Mailbag",
    id: "BPMailbag",
    desc: "Increases the wearer's overall carry capacity by +15. A pre-war U.S. Mail carrier bag repurposed for hauling supplies.",
    location: "ThicketExcavationsExt04 — Thicket Excavations",
    cc: "+15 / +20 / +25 CC",
    dr: "+2 DR → +10 DR",
    special: [],
    crafting: "Adhesive ×4 · Leather ×4 · Duct Tape ×1 · Cloth ×7",
    weight: "2 lbs",
    value: "78 caps",
    colors: ["Default"],
    upgrades: ["+15 CC Base", "+20 CC Reinforced", "+25 CC Heavy Duty"]
  },
  {
    num: 3, level: 5,
    name: "Leather Shoulder Bag",
    id: "BPLeather",
    desc: "Increases the wearer's overall carry capacity by +20. Rugged leather construction.",
    location: "DrumlinDiner — Drumlin Diner",
    cc: "+20 / +25 CC",
    dr: "+5 DR → +15 DR",
    special: [],
    crafting: "Adhesive ×4 · Leather ×8 · Wonderglue ×1 · Cloth ×4",
    weight: "2 lbs",
    value: "97 caps",
    colors: ["Brown Leather", "Black Leather"],
    upgrades: ["+20 CC Base", "+25 CC Reinforced"]
  },
  {
    num: 4, level: 10,
    name: "Raider's Harnessed Metal Container",
    id: "BPRaider",
    desc: "Increases the wearer's overall carry capacity by +30. -1 Agility. Jury-rigged from scrap metal and salvaged straps.",
    location: "FederalRationStockpileExt — Federal Ration Stockpile",
    cc: "+30 / +35 CC",
    dr: "+10 DR → +30 DR",
    special: ["-1 AGI", "→ +0 AGI"],
    crafting: "Adhesive ×5 · Leather ×8 · Steel ×5 · Screw ×3 · Metal Bucket ×1 · [Armorer I]",
    weight: "5 lbs",
    value: "135 caps",
    colors: ["Default"],
    upgrades: ["+30 CC | -1 AGI Base", "+35 CC | +0 AGI Reinforced"]
  },
  {
    num: 5, level: 15,
    name: "Outcast's Travel Pouch",
    id: "BPOutcast",
    desc: "Increases the wearer's overall carry capacity by +25. -2 Agility. Standard field pack used by Brotherhood Outcasts.",
    location: "SuperDuperMart01 — Super Duper Mart",
    cc: "+25 / +30 / +35 / +40 CC",
    dr: "+5 DR → +20 DR",
    special: ["-2 AGI", "-1 AGI", "+0 AGI", "+1 END"],
    crafting: "Aluminum ×3 · Adhesive ×5 · Leather ×5 · Cloth ×8 · Brahmin Hide ×1 · [Armorer I]",
    weight: "3 lbs",
    value: "213 caps",
    colors: ["Green", "Tan"],
    upgrades: ["+25 CC | -2 AGI", "+30 CC | -1 AGI", "+35 CC | +0 AGI", "+40 CC | +1 END"]
  },
  {
    num: 6, level: 15,
    name: "Makeshift Backpack",
    id: "BPMakeshift",
    desc: "Increases the wearer's overall carry capacity by +30. -1 Agility. Cobbled together from whatever was lying around.",
    location: "MaldenCenter01 — Malden Center",
    cc: "+30 / +35 / +40 CC",
    dr: "+10 DR → +20 DR",
    special: ["-1 AGI", "+0 AGI", "+1 LCK (Lucky)"],
    crafting: "Adhesive ×5 · Leather ×5 · Steel ×3 · Duct Tape ×1 · Bag of Cement ×1 · Cloth ×9",
    weight: "4 lbs",
    value: "232 caps",
    colors: ["Default"],
    upgrades: ["+30 CC | -1 AGI", "+35 CC | -1 AGI", "+40 CC Water | +0 AGI", "+40 CC Lucky | +1 LCK"]
  },
  {
    num: 7, level: 20,
    name: "Trapper's Back Pouch",
    id: "BPTrapper",
    desc: "Increases the wearer's overall carry capacity by +35. -1 Agility. Stitched from animal hides. Bonus damage against animals and sea creatures.",
    location: "BADTFL01 — BADTFL Regional Office",
    cc: "+35 / +40 / +45 CC",
    dr: "+5 DR → +15 DR → +30 DR",
    special: ["-1 AGI", "+0 AGI", "Bug Dmg Bonus"],
    crafting: "Aluminum ×3 · Bone ×3 · Adhesive ×5 · Leather ×8 · Cloth ×5 · Radstag Hide ×1 · [Armorer I]",
    weight: "3 lbs",
    value: "281 caps",
    colors: ["Default"],
    upgrades: ["+35 CC | -1 AGI | Bug Dmg", "+40 CC | -1 AGI | Bug Dmg", "+45 CC | +0 AGI | Bug Dmg"]
  },
  {
    num: 8, level: 20,
    name: "Bedroll Backpack",
    id: "BPBedroll",
    desc: "Increases the wearer's overall carry capacity by +30. -1 Agility. Doubles as a bedroll for long hauls in the field.",
    location: "LynnWoodsExt02 — Lynn Woods",
    cc: "+30 / +35 / +40 / +45 CC",
    dr: "+8 DR",
    special: ["-1 AGI", "+0 AGI", "+1 CHR (Charisma)"],
    crafting: "Adhesive ×6 · Leather ×6 · Straw Pillow ×1 · Comfy Pillow ×1 · Cloth ×10",
    weight: "4 lbs",
    value: "339 caps",
    colors: ["Default"],
    upgrades: ["+30 CC | -1 AGI", "+35 CC | +0 AGI", "+40 CC | +0 AGI", "+45 CC | +1 CHR"]
  },
  {
    num: 9, level: 25,
    name: "Military Duffle Bag",
    id: "BPDuffle",
    desc: "Increases the wearer's overall carry capacity by +40. -1 Agility. Surplus military canvas bag. Designed for quick access in the field.",
    location: "NationalGuardTrainingYard03 — National Guard Training Yard",
    cc: "+40 / +45 / +50 CC",
    dr: "+10 DR → +20 DR",
    special: ["-1 AGI", "+0 AGI", "+Reload Speed"],
    crafting: "Aluminum ×4 · Adhesive ×7 · Leather ×7 · Military Ammo Bag ×1 · Cloth ×10 · [Armorer II]",
    weight: "4 lbs",
    value: "377 caps",
    colors: ["Default", "Blue"],
    upgrades: ["+40 CC | -1 AGI | +Reload", "+45 CC | -1 AGI | +Reload", "+50 CC | +0 AGI | +Reload"]
  },
  {
    num: 10, level: 25,
    name: "Tinker's Rucksack",
    id: "BPTinker",
    desc: "Increases the wearer's overall carry capacity by +40. -2 Agility. Overbuilt and overloaded. Every pocket filled with something useful.",
    location: "BeantownBrewery01 — Beantown Brewery",
    cc: "+40 / +45 / +50 CC",
    dr: "+25 DR → +35 DR",
    special: ["-2 AGI", "-1 AGI", "+0 AGI"],
    crafting: "Adhesive ×7 · Leather ×8 · Gear ×4 · Screw ×3 · Adjustable Wrench ×1 · Cloth ×6 · [Armorer II]",
    weight: "6 lbs",
    value: "412 caps",
    colors: ["Default"],
    upgrades: ["+40 CC | -2 AGI", "+45 CC | -1 AGI", "+45 CC Plus | -1 AGI", "+50 CC | +0 AGI", "+50 CC Plus | +0 AGI"]
  },
  {
    num: 11, level: 30,
    name: "Sling Pouch",
    id: "BPSling",
    desc: "Increases the wearer's overall carry capacity by +40. -1 Agility. Improves AP regeneration when under pressure.",
    location: "HubrisComics01 — Hubris Comics",
    cc: "+40 / +45 / +50 / +55 CC",
    dr: "+5 DR",
    special: ["-1 AGI", "+0 AGI", "+10–20 AP Regen"],
    crafting: "Battered Clipboard ×1 · Adhesive ×7 · Leather ×8 · Rubber ×3 · Cloth ×5 · Tongs ×1 · [Armorer II]",
    weight: "2 lbs",
    value: "349 caps",
    colors: ["Default"],
    upgrades: ["+40 CC | -1 AGI | +10 AP Regen", "+45 CC | +0 AGI | +15 AP Regen", "+50 CC | +0 AGI | +20 AP Regen", "+55 CC | +0 AGI | +20 AP Sprint Regen"]
  },
  {
    num: 12, level: 30,
    name: "Mountaineer's Backpack",
    id: "BPMountaineer",
    desc: "Increases the wearer's overall carry capacity by +45. -1 Agility. Reinforced frame built for long treks across rough terrain.",
    location: "WestEverettEstates01 — West Everett Estates",
    cc: "+45 / +50 / +55 CC",
    dr: "+15 DR",
    special: ["-1 AGI", "+0 AGI", "+1 END (Endurance)"],
    crafting: "Aluminum ×4 · Adhesive ×8 · Leather ×7 · Military Grade Duct Tape ×1 · Cloth ×10 · [Armorer II]",
    weight: "4 lbs",
    value: "438 caps",
    colors: ["Green", "Blue", "Rose"],
    upgrades: ["+45 CC | -1 AGI", "+50 CC | +0 AGI", "+55 CC | +0 AGI | +1 END"]
  },
  {
    num: 13, level: 30,
    name: "Wastelander's Backpack",
    id: "BPWastelander",
    desc: "Increases the wearer's overall carry capacity by +50. -1 Agility. A survivor's pack built for the long haul.",
    location: "BackBayFence01 — Trinity Tower area",
    cc: "+50 / +55 / +60 CC",
    dr: "+20 DR",
    special: ["-1 AGI", "+0 AGI", "+Water", "+Rad Scrub"],
    crafting: "Aluminum ×4 · Adhesive ×8 · Leather ×8 · Cloth ×10 · Molerat Hide ×2 · [Armorer II]",
    weight: "3 lbs",
    value: "467 caps",
    colors: ["Green", "Blue"],
    upgrades: ["+50 CC | -1 AGI", "+55 CC | +0 AGI", "+60 CC | +0 AGI", "+60 CC | +Water Mgmt", "+60 CC | +Water+Rads"]
  },
  {
    num: 14, level: 35,
    name: "Squire's Backpack",
    id: "BPSquire",
    desc: "Increases the wearer's overall carry capacity by +50. -2 Agility. Standard issue for Brotherhood of Steel initiates.",
    location: "BostonAirportRuins01 — Boston Airport Ruins",
    cc: "+50 / +55 / +60 CC",
    dr: "+10 DR → +20 DR → +30 DR",
    special: ["-2 AGI", "-1 AGI", "+0 AGI", "+1 END"],
    crafting: "Ballistic Fiber ×2 · Adhesive ×8 · Leather ×9 · Baseball ×1 · Basketball ×1 · Cloth ×7 · [Armorer II]",
    weight: "3 lbs",
    value: "528 caps",
    colors: ["Brown Leather", "Army Green Canvas", "Black Leather"],
    upgrades: ["+50 CC | -2 AGI", "+55 CC | -1 AGI", "+60 CC | +0 AGI", "+60 CC Plus | +1 END"]
  },
  {
    num: 15, level: 35,
    name: "Super Mutant's Trunk",
    id: "BPMutant",
    desc: "Increases the wearer's overall carry capacity by +50. -2 Agility. Ripped from a super mutant's camp and barely repurposed.",
    location: "BigJohnsSalvage01 — Big John's Salvage (shelter)",
    cc: "+50 / +55 / +60 / +65 CC",
    dr: "+30 DR → +40 DR",
    special: ["-2 AGI", "-1 AGI", "+0 AGI", "+1 END", "+1 LCK (Lucky)"],
    crafting: "Ballistic Fiber ×3 · Adhesive ×8 · Leather ×11 · Steel ×7 · Shopping Basket ×1 · [Armorer II]",
    weight: "9 lbs",
    value: "489 caps",
    colors: ["Default"],
    upgrades: ["+50 CC | -2 AGI", "+55 CC | -1 AGI", "+60 CC | +0 AGI", "+65 CC Lucky | +1 LCK", "+65 CC Unarmed | +0 AGI"]
  },
  {
    num: 16, level: 35,
    name: "Manpack Portable Radio Transceiver",
    id: "BPRadio",
    desc: "Increases the wearer's overall carry capacity by +50. -2 Agility. Repurposed military radio unit. Improves targeting accuracy in V.A.T.S.",
    location: "POIJoel06 — Exterior of Hester's",
    cc: "+50 / +55 / +60 / +65 CC",
    dr: "+30 DR | +5 ER",
    special: ["-2 AGI", "-1 AGI", "+0 AGI", "+VATS Accuracy"],
    crafting: "Aluminum ×7 · Circuitry ×3 · Adhesive ×4 · Leather ×7 · Vacuum Tube ×1 · Sensor Module ×1 · [Science! I]",
    weight: "7 lbs",
    value: "531 caps",
    colors: ["Default"],
    upgrades: ["+50 CC | -2 AGI | VATS", "+55 CC | -1 AGI | VATS", "+60 CC | +0 AGI | VATS", "+65 CC | +0 AGI | VATS"]
  },
  {
    num: 17, level: 40,
    name: "R.O.B.B. Personal Carrying Device Mk I",
    id: "BPStealth",
    desc: "Increases the wearer's overall carry capacity by +55. -1 Agility. R.O.B.B.-series robotic carrying frame with integrated sensor array.",
    location: "InstituteAdvSystems — Institute Advanced Systems",
    cc: "+55 / +60 / +65 CC",
    dr: "+20 DR",
    special: ["-1 AGI", "+0 AGI", "+1 END", "+Sneak", "+Water/Rads"],
    crafting: "Aluminum ×8 · Circuitry ×4 · Adhesive ×9 · Leather ×7 · Biometric Scanner ×1 · Sensor Module ×1 · [Science! I]",
    weight: "6 lbs",
    value: "590 caps",
    colors: ["Default"],
    upgrades: ["+55 CC | -1 AGI", "+60 CC Sneak | +0 AGI", "+65 CC Plus | +0 AGI", "+65 CC Rads | +1 END", "+65 CC Water+Rads | +1 END"]
  },
  {
    num: 18, level: 40,
    name: "Limited Edition Nuka-Pack!",
    id: "BPNuka",
    desc: "Increases the wearer's overall carry capacity by +60. Nuka-Cola branded collector's pack. Compatible with a wide range of Nuka upgrades.",
    location: "DLC04BradbertonsOffice01 — Bradberton's Office (Nuka-World)",
    cc: "+60 / +65 / +70 / +100 / +110 CC",
    dr: "+20 DR | +10 ER",
    special: ["+2 INT", "+2 END", "+2 PER", "+2 AGI", "+2 STR", "+2 LCK"],
    crafting: "Aluminum ×8 · Adhesive ×9 · Nuclear Material ×3 · Nuka-Cola ×6 · Military-Grade Circuit Board ×1 · Assaultron Circuit Board ×1 · [Science! II]",
    weight: "6 lbs",
    value: "893 caps",
    colors: ["Many Nuka variants"],
    upgrades: ["+60 CC Base", "+65 CC | +2 INT/STR/etc", "+70 CC Max HP/AP", "+70 CC | +20DR/+20RR", "+70 CC Rads", "+100 CC", "+110 CC"]
  },
  {
    num: 19, level: 45,
    name: "Junkie's Chem Stash",
    id: "BPChem",
    desc: "Increases the wearer\'s overall carry capacity by +55. -2 Agility. The more wrecked you are, the better it works.",
    location: "FourLeafFishpacking02 — Four Leaf Fishpacking Plant",
    cc: "+55 / +60 / +65 / +70 CC",
    dr: "+10 DR",
    special: ["-2 AGI", "-1 AGI", "+0 AGI", "+5% Dmg Resist per Chem"],
    crafting: "Adhesive ×8 · Leather ×7 · Mentats ×1 · Psycho ×1 · Table Spoon ×1 · Cloth ×9 · [Chemist I]",
    weight: "5 lbs",
    value: "569 caps",
    colors: ["Default"],
    upgrades: ["+55 CC | -2 AGI | +Add 5", "+60 CC | -1 AGI | +Add 5/5", "+65 CC | +0 AGI | +Add 5/10", "+70 CC | +0 AGI | +Add 10/10"]
  },
  {
    num: 20, level: 45,
    name: "Scribe's Backpack",
    id: "BPScribe",
    desc: "Increases the wearer's overall carry capacity by +60. -2 Agility. Brotherhood Scribe-issue pack. Built for long research expeditions.",
    location: "VirgilsLab01 — Virgil's Laboratory (Glowing Sea)",
    cc: "+60 / +65 / +70 / +75 CC",
    dr: "+10 DR",
    special: ["-2 AGI", "-1 AGI", "+0 AGI", "+1 END"],
    crafting: "Ballistic Fiber ×4 · Adhesive ×9 · Leather ×8 · Military Grade Duct Tape ×1 · Cloth ×10 · Military-Grade Circuit Board ×1 · [Science! I, Armorer II]",
    weight: "4 lbs",
    value: "642 caps",
    colors: ["Default"],
    upgrades: ["+60 CC | -2 AGI", "+65 CC | -1 AGI", "+70 CC | +0 AGI", "+75 CC | +1 END"]
  },
  {
    num: 21, level: 50,
    name: "Military Backpack",
    id: "BPMilitary",
    desc: "Increases the wearer's overall carry capacity by +70. -1 Agility. Standard U.S. Army issue field pack.",
    location: "QuincyRuinsExt — Quincy Ruins",
    cc: "+70 / +75 / +80 CC",
    dr: "+10 DR → +30 DR",
    special: ["-1 AGI", "+0 AGI", "+1 END", "+Reload Speed"],
    crafting: "Ballistic Fiber ×3 · Adhesive ×10 · Leather ×9 · Military Ammo Bag ×1 · Military Grade Duct Tape ×1 · Cloth ×11 · [Armorer II]",
    weight: "3 lbs",
    value: "701 caps",
    colors: ["Rebel Canvas", "U.S. Army Green", "Dark Blood Ruby", "Shadow Black"],
    upgrades: ["+70 CC | -1 AGI", "+75 CC | +0 AGI", "+80 CC | +1 END", "+80 CC | +0 AGI | +Reload"]
  },
  {
    num: 22, level: 50,
    name: "G.A.R.I. Personal Carrying Device Mk II",
    id: "BPBattery",
    desc: "Increases the wearer's overall carry capacity by +80. -1 Agility. Experimental pre-war carrying unit powered by a fusion core.",
    location: "GlowingSeaPOIRJ03 — Decayed Reactor Site (Glowing Sea)",
    cc: "+80 / +85 CC",
    dr: "+10 DR | +20 ER",
    special: ["-1 AGI", "+0 AGI", "+Jump Height", "+Dmg Bonus"],
    crafting: "Aluminum ×10 · Circuitry ×4 · Fiber Optics ×3 · Adhesive ×9 · Leather ×8 · Fusion Core ×1 · Military-Grade Circuit Board ×1 · [Armorer II, Science! II]",
    weight: "8 lbs",
    value: "843 caps",
    colors: ["Default"],
    upgrades: ["+80 CC | -1 AGI", "+85 CC | +0 AGI | +Dmg", "+85 CC | +0 AGI | +Jump"]
  },
  {
    num: 23, level: 55,
    name: "Woodsman's Backpack",
    id: "BPWoodsman",
    desc: "Increases the wearer's overall carry capacity by +75. -2 Agility. Built for wilderness survival. Includes a built-in knife sharpening sheath.",
    location: "MuseumOfWitchcraft01 — Museum of Witchcraft",
    cc: "+75 / +80 / +85 / +90 CC",
    dr: "+15 DR",
    special: ["-2 AGI", "-1 AGI", "+1 END", "+Melee Dmg", "+Sneak", "+Water"],
    crafting: "Adhesive ×9 · Leather ×11 · Oil ×3 · Comfy Pillow ×1 · Cloth ×11 · Hack Saw ×1 · [Armorer III]",
    weight: "4 lbs",
    value: "853 caps",
    colors: ["Black", "Orange Rust"],
    upgrades: ["+75 CC | -2 AGI", "+80 CC | -1 AGI", "+85 CC | +0 AGI | +Water", "+85 CC | +0 AGI | +Melee", "+90 CC | +0 AGI | +Sneak"]
  },
  {
    num: 24, level: 55,
    name: "Mercenary's Rucksack",
    id: "BPMercenary",
    desc: "Increases the wearer's overall carry capacity by +80. -1 Agility. Heavy-duty military-grade rucksack favored by Gunners.",
    location: "GNN01 — Gunner's Plaza",
    cc: "+80 / +85 CC",
    dr: "+10 DR → +20 DR",
    special: ["-1 AGI", "+1 END", "+Reload Speed"],
    crafting: "Aluminum ×5 · Ballistic Fiber ×4 · Adhesive ×10 · Leather ×11 · Military Ammo Bag ×2 · Cloth ×10 · [Armorer III]",
    weight: "4 lbs",
    value: "864 caps",
    colors: ["Khaki", "Green", "Brown"],
    upgrades: ["+80 CC | -1 AGI", "+85 CC | -1 AGI", "+85 CC | +1 END | +Reload"]
  },
  {
    num: 25, level: 60,
    name: "Vault-Tec Utility Backpack",
    id: "BPVault",
    desc: "Increases the wearer's overall carry capacity by +90. -2 Agility. Vault-Tec engineered utility pack. Features a bobblehead keychain attachment.",
    location: "Vault95 — Vault 95",
    cc: "+90 / +95 / +100 CC",
    dr: "+10 DR | +10 RR",
    special: ["-2 AGI", "+0 AGI", "+1 CHR", "+Charisma", "+Small Guns", "+Energy", "+Sneak"],
    crafting: "Circuitry ×5 · Adhesive ×12 · Leather ×12 · Nuclear Material ×4 · Cloth ×12 · Biometric Scanner ×1 · Vault-Tec Lunchbox ×1 · [Armorer III]",
    weight: "5 lbs",
    value: "1,011 caps",
    colors: ["Default"],
    upgrades: ["+90 CC | -2 AGI", "+95 CC | +0 AGI", "+100 CC | +1 CHR", "+100 CC | +Small Guns", "+100 CC | +Energy", "+100 CC | +Sneak"]
  },
  {
    num: 26, level: 65,
    name: "P.E.G.A. Fusion Powered P.C.D. Mk III",
    id: "BPFusion",
    desc: "Increases the wearer's overall carry capacity by +85. -2 Agility. The pinnacle of pre-war personal carrying technology. Fusion-powered.",
    location: "BackpackRoom — Boston Backpacks HQ (discoverable location)",
    cc: "+85 / +90 / +95 / +100 CC",
    dr: "+30 DR | +10 ER | +10 RR → +50 DR | +20 ER | +30 RR",
    special: ["-2 AGI", "-1 AGI", "+0 AGI", "+1 END", "+Water/Rads"],
    crafting: "Aluminum ×12 · Ballistic Fiber ×6 · Circuitry ×6 · Adhesive ×12 · Nuclear Material ×4 · Fusion Core ×2 · High-Powered Magnet ×1 · [Science! III, Armorer III]",
    weight: "7 lbs",
    value: "1,137 caps",
    colors: ["Yellow", "Green", "Red", "Purple", "Orange", "Blue"],
    upgrades: ["+85 CC | -2 AGI", "+90 CC | -1 AGI", "+95 CC | +0 AGI", "+100 CC Plus | +0 AGI", "+100 CC Water+Rads | +0 AGI", "+100 CC W+R+Plus | +0 AGI"]
  },
  {
    num: 27, level: 70,
    name: "RobCo Nukatility Combo Pack",
    id: "BPRobCo",
    desc: "Increases the wearer's overall carry capacity by +85. -1 Agility. Chills one Nuka-Cola or Nuka-Cherry to its Ice-Cold variant every six hours.",
    location: "AtomatoysFactoryExt — Wilson Atomatoys Factory",
    cc: "+85 / +90 / +100 CC",
    dr: "+15 DR | +10 RR → +30 DR | +15 ER | +30 RR",
    special: ["-1 AGI", "+0 AGI", "+15 AP"],
    crafting: "Cloth ×16 · Aluminum ×8 · Adhesive ×4 · Screw ×4 · Circuitry ×3 · Copper ×3 · Gear ×3 · [Armorer III, Science! III]",
    weight: "6 lbs",
    value: "1,196 caps",
    colors: ["Default", "Olive Nuka Red", "Quantum Violet"],
    upgrades: ["+85 CC | -1 AGI", "+90 CC | +0 AGI", "+100 CC | +15 AP"]
  },
  {
    num: 28, level: 75,
    name: "Brotherhood S.E.N.T.R.Y. Device",
    id: "BPSentry",
    desc: "Increases the wearer's overall carry capacity by +90. -2 Agility. +25 DR, +15 ER. Reconnaissance Burst outlines nearby enemies in red for 6 seconds during combat or while sneaking with a weapon drawn; 60-second recharge.",
    location: "FortStrong02 — Fort Strong equipment cage",
    cc: "+90 / +95 / +100 CC",
    dr: "+25 DR | +15 ER → +40 DR | +35 ER | +20 RR",
    special: ["-2 AGI", "-1 AGI", "+0 AGI", "+10% VATS", "+Reactive Aegis"],
    crafting: "Aluminum ×12 · Steel ×10 · Circuitry ×5 · Fiber Optics ×4 · Adhesive ×4 · Screw ×4 · Gear ×3 · Nuclear Material ×2 · Military-Grade Circuit Board ×1 · Fusion Core ×1 · [Armorer IV, Science! IV]",
    weight: "8 lbs",
    value: "1,239 caps",
    colors: ["Gunmetal/Black", "Olive/Steel"],
    upgrades: ["+90 CC | -2 AGI", "+95 CC | -1 AGI", "+100 CC | +10% VATS", "+100 CC | Reactive Aegis"]
  },
  {
    num: 29, level: 80,
    name: "Arc-tesla P.C.D. Mk IV",
    id: "BPArc",
    desc: "Increases the wearer's overall carry capacity by +100. Incoming combat impacts accelerate Capacitor Overload; at full charge, your next weapon bash releases a Tesla burst that can arc to two nearby hostiles.",
    location: "BackpackBunker — Vault-Tec Bunker Sigma (Master-locked display case)",
    cc: "+100 / +110 CC",
    dr: "+30 DR | +30 ER | +15 RR",
    special: ["+0 AGI", "+Capacitor Overload"],
    crafting: "Aluminum ×14 · Adhesive ×12 · Circuitry ×8 · Copper ×8 · Ceramic ×6 · Fiber Optics ×4 · Nuclear Material ×4 · High-Powered Magnet ×1 · Fusion Core ×2 · [Armorer IV, Science! IV]",
    weight: "8 lbs",
    value: "1,450 caps",
    colors: ["Default"],
    upgrades: ["+100 CC | +0 AGI", "+110 CC | +0 AGI"]
  }
];

// Workbench mods per backpack editor ID: cc = carry-capacity mods, dr = resistance mods.
const OMODS = {"BPShoulder": {"cc": [{"name": "Cloth Bag", "desc": "Increases the wearer's overall carry capacity by +10.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Additional Cloth Pouch", "desc": "Increases the wearer's overall carry capacity by +15.", "perks": ["Armorer I"], "ingredients": ["Adhesive ×3", "Cloth ×7"]}, {"name": "Large Cloth Bag", "desc": "Increases the wearer's overall carry capacity by +20.", "perks": ["Armorer I"], "ingredients": ["Adhesive ×5", "Cloth ×10"]}], "dr": []}, "BPMailbag": {"cc": [{"name": "Cloth Frame", "desc": "Increases the wearer's overall carry capacity by +15.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Flexible Cloth Frame", "desc": "Increases the wearer's overall carry capacity by +20.", "perks": ["Armorer I"], "ingredients": ["Adhesive ×3", "Leather ×2", "Cloth ×4"]}, {"name": "Additional Pocket", "desc": "Increases the wearer's overall carry capacity by +25.", "perks": ["Armorer I"], "ingredients": ["Adhesive ×4", "Leather ×3", "Cloth ×7"]}], "dr": [{"name": "Cloth Shell", "desc": "Damage resistance +2.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Hardened Cloth Shell", "desc": "Damage resistance +10.", "perks": ["Armorer I"], "ingredients": ["Adhesive ×2", "Leather ×4"]}]}, "BPLeather": {"cc": [{"name": "Leather Frame", "desc": "Increases the wearer's overall carry capacity by +20.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Sturdy Leather Frame", "desc": "Increases the wearer's overall carry capacity by +25.", "perks": ["Armorer I"], "ingredients": ["Adhesive ×3", "Leather ×4", "Cloth ×4"]}], "dr": [{"name": "Leather Shell", "desc": "Damage resistance +5.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Treated Leather Shell", "desc": "Damage resistance +15.", "perks": ["Armorer I"], "ingredients": ["Aluminum ×1", "Adhesive ×2", "Leather ×4"]}]}, "BPRaider": {"cc": [{"name": "Aluminum Frame", "desc": "Increases the wearer's overall carry capacity by +30. -1 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Softened Metal Frame", "desc": "Increases the wearer's overall carry capacity by +35.", "perks": ["Armorer I", "Strong Back I"], "ingredients": ["Aluminum ×4", "Adhesive ×3", "Leather ×4"]}], "dr": [{"name": "Aluminum Plating", "desc": "Damage resistance +10.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Steel Plating", "desc": "Damage resistance +30.", "perks": ["Armorer I"], "ingredients": ["Aluminum ×4", "Adhesive ×2", "Leather ×2"]}]}, "BPOutcast": {"cc": [{"name": "Leather Frame", "desc": "Increases the wearer's overall carry capacity by +25. -2 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Sturdy Leather Frame", "desc": "Increases the wearer's overall carry capacity by +30. -1 Agility.", "perks": ["Armorer I", "Strong Back I"], "ingredients": ["Adhesive ×2", "Leather ×8", "Plastic ×2", "Cloth ×6"]}, {"name": "Reinforced Leather Frame", "desc": "Increases the wearer's overall carry capacity by +35.", "perks": ["Armorer II", "Strong Back I"], "ingredients": ["Adhesive ×3", "Leather ×8", "Plastic ×2", "Cloth ×10"]}, {"name": "Strengthened Leather Frame", "desc": "Increases the wearer's overall carry capacity by +40. +1 Endurance.", "perks": ["Armorer II", "Strong Back II"], "ingredients": ["Adhesive ×3", "Leather ×12", "Plastic ×2", "Cloth ×10"]}], "dr": [{"name": "Canvas Shell", "desc": "Damage resistance +5.", "perks": ["Armorer I"], "ingredients": ["Adhesive ×1"]}, {"name": "Hardened Canvas Shell", "desc": "Damage resistance +20.", "perks": ["Armorer II"], "ingredients": ["Acid ×2", "Adhesive ×3", "Leather ×8"]}]}, "BPMakeshift": {"cc": [{"name": "Leather Frame", "desc": "Increases the wearer's overall carry capacity by +30. -1 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Sturdy Leather Frame", "desc": "Increases the wearer's overall carry capacity by +35. -1 Agility.", "perks": ["Armorer I", "Strong Back I"], "ingredients": ["Adhesive ×4", "Leather ×6", "Plastic ×2", "Cloth ×6"]}, {"name": "Strengthened Leather Frame", "desc": "Increases the wearer's overall carry capacity by +40.", "perks": ["Armorer II", "Strong Back I"], "ingredients": ["Adhesive ×5", "Leather ×8", "Plastic ×2", "Cloth ×6"]}, {"name": "Strapped Water Canteen", "desc": "Increases the wearer's overall carry capacity by +40. Fresh water drink periodically.", "perks": ["Armorer II", "Lead Belly I"], "ingredients": ["Adhesive ×4", "Leather ×4", "Plastic ×2", "Purified Water ×1", "Cloth ×2"]}, {"name": "Lucky Sloth", "desc": "Increases the wearer's overall carry capacity by +40. +1 Luck.", "perks": ["Armorer II", "Local Leader I"], "ingredients": ["Adhesive ×6", "Leather ×4", "Plastic ×2", "Souvenir Sloth Toy ×1"]}], "dr": [{"name": "Leather Shell", "desc": "Damage resistance +10.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Hardened Leather Shell", "desc": "Damage resistance +20.", "perks": ["Armorer II"], "ingredients": ["Adhesive ×2", "Leather ×4", "Plastic ×2", "Cloth ×2"]}]}, "BPTrapper": {"cc": [{"name": "Leather Frame", "desc": "Increases the wearer's overall carry capacity by +35. -1 Agility. +10% damage against animals and sea creatures.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Sturdy Leather Frame", "desc": "Increases the wearer's overall carry capacity by +40. +20% damage against animals and sea creatures.", "perks": ["Armorer II", "Strong Back I"], "ingredients": ["Adhesive ×3", "Leather ×8", "Cloth ×6"]}, {"name": "Reinforced Leather Frame", "desc": "Increases the wearer's overall carry capacity by +40. +20% damage against animals and sea creatures.", "perks": ["Armorer III", "Toughness I"], "ingredients": ["Aluminum ×8", "Adhesive ×5", "Leather ×10", "Cloth ×6"]}], "dr": [{"name": "Brahmin Leather Shell", "desc": "Damage resistance +5.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Radstag Leather Shell", "desc": "Damage resistance +15.", "perks": ["Armorer I", "Strong Back I"], "ingredients": ["Adhesive ×2", "Leather ×6", "Plastic ×2"]}, {"name": "Yao Guai Hide Shell", "desc": "Damage resistance +30.", "perks": ["Armorer II", "Strong Back I"], "ingredients": ["Adhesive ×3", "Leather ×10", "Plastic ×2", "Cloth ×2"]}]}, "BPBedroll": {"cc": [{"name": "Single Pouch", "desc": "Increases the wearer's overall carry capacity by +30. -1 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Additional Side Pouch", "desc": "Increases the wearer's overall carry capacity by +35.", "perks": ["Armorer I"], "ingredients": ["Adhesive ×2", "Leather ×8", "Plastic ×2", "Cloth ×6"]}, {"name": "Brahamin Leather Frame", "desc": "Increases the wearer's overall carry capacity by +40.", "perks": ["Armorer II"], "ingredients": ["Adhesive ×4", "Leather ×10", "Plastic ×2", "Cloth ×6"]}, {"name": "Souvenir Badges", "desc": "Increases the wearer's overall carry capacity by +45. +1 Charisma.", "perks": ["Armorer II", "Local Leader II"], "ingredients": ["Adhesive ×5", "Souvenir Magnet Cow ×1", "Souvenir Magnet Badge ×1", "Souvenir Magnet Flower ×1", "Souvenir Magnet Frog ×1", "Souvenir Magnet Cat ×1"]}], "dr": []}, "BPDuffle": {"cc": [{"name": "Large Bag", "desc": "Increases the wearer's overall carry capacity by +40. -1 Agility. Weapon reload speed slightly increased.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Side Pouch", "desc": "Increases the wearer's overall carry capacity by +45. Weapon reload speed slightly increased.", "perks": ["Armorer I", "Strong Back I"], "ingredients": ["Adhesive ×3", "Leather ×8", "Cloth ×6"]}, {"name": "Ammo Strap", "desc": "Increases the wearer's overall carry capacity by +50. Weapon reload speed slightly increased.", "perks": ["Armorer II", "Commando I"], "ingredients": ["Adhesive ×3", "Leather ×10", "Steel ×6", "Cloth ×6"]}], "dr": [{"name": "Canvas Shell", "desc": "Damage resistance +10.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Reinforced Canvas Shell", "desc": "Damage resistance +20.", "perks": ["Armorer II"], "ingredients": ["Adhesive ×2", "Leather ×6", "Plastic ×2", "Steel ×4"]}]}, "BPTinker": {"cc": [{"name": "Brahmin Leather Frame", "desc": "Increases the wearer's overall carry capacity by +40. -2 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Additional Canvas Bag", "desc": "Increases the wearer's overall carry capacity by +45. -2 Agility.", "perks": ["Armorer I", "Strong Back I"], "ingredients": ["Adhesive ×2", "Leather ×4", "Plastic ×2", "Cloth ×6"]}, {"name": "Stash Toolbox", "desc": "Increases the wearer's overall carry capacity by +50. -1 Agility.", "perks": ["Armorer I", "Strong Back I"], "ingredients": ["Aluminum ×6", "Adhesive ×2", "Leather ×4", "Screw ×2"]}, {"name": "Extra Leather Pouch", "desc": "Increases the wearer's overall carry capacity by +55.", "perks": ["Armorer II", "Strong Back I"], "ingredients": ["Aluminum ×10", "Adhesive ×4", "Leather ×8", "Cloth ×2"]}, {"name": "Strapped Water Flask", "desc": "Increases the wearer's overall carry capacity by +55. Fresh water drink periodically.", "perks": ["Armorer II", "Lead Belly I"], "ingredients": ["Adhesive ×4", "Leather ×4", "Plastic ×4", "Purified Water ×2", "Cloth ×2"]}], "dr": []}, "BPSling": {"cc": [{"name": "Small Pouch", "desc": "Increases the wearer's overall carry capacity by +40. -1 Agility. Increased AP regeneration rate when AP is below 10%.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Medium Pouch", "desc": "Increases the wearer's overall carry capacity by +45. Increased AP regeneration rate when AP is below 15%.", "perks": ["Armorer II"], "ingredients": ["Adhesive ×3", "Leather ×7", "Psycho ×2", "Jet ×1"]}, {"name": "Large Pouch", "desc": "Increases the wearer's overall carry capacity by +50. Increased AP regeneration rate when AP is below 20%.", "perks": ["Armorer III", "Chemist I"], "ingredients": ["Adhesive ×4", "Leather ×8", "Psycho ×2", "Jet ×4"]}, {"name": "Large Pouch with Action Belt", "desc": "Increases the wearer's overall carry capacity by +55. Significantly increased AP regeneration rate when AP is below 20%.", "perks": ["Armorer IV", "Chemist II"], "ingredients": ["Adhesive ×6", "Leather ×10", "Psycho Jet ×5"]}], "dr": []}, "BPMountaineer": {"cc": [{"name": "Leather Frame", "desc": "Increases the wearer's overall carry capacity by +45. -1 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Sturdy Leather Frame", "desc": "Increases the wearer's overall carry capacity by +50.", "perks": ["Armorer II", "Strong Back II"], "ingredients": ["Adhesive ×4", "Leather ×6", "Plastic ×2", "Cloth ×4"]}, {"name": "Reinforced Leather Frame", "desc": "Increases the wearer's overall carry capacity by +55. +1 Endurance.", "perks": ["Armorer III", "Toughness I"], "ingredients": ["Adhesive ×6", "Leather ×10", "Plastic ×5", "Cloth ×5"]}], "dr": []}, "BPWastelander": {"cc": [{"name": "Canvas Frame", "desc": "Increases the wearer's overall carry capacity by +50. -1 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Sturdy Canvas Frame", "desc": "Increases the wearer's overall carry capacity by +55. -1 Agility.", "perks": ["Armorer II", "Strong Back I"], "ingredients": ["Adhesive ×3", "Leather ×5", "Plastic ×2", "Cloth ×2"]}, {"name": "Strengthened Canvas Frame", "desc": "Increases the wearer's overall carry capacity by +60.", "perks": ["Armorer III", "Chemist I"], "ingredients": ["Adhesive ×5", "Leather ×6", "Plastic ×2", "Rad-X ×1", "Purified Water ×1", "Cloth ×4"]}, {"name": "Water Bottle with Rad-X Pouch", "desc": "Increases the wearer's overall carry capacity by +60. Fresh water drink and rads removed periodically.", "perks": ["Armorer III", "Lead Belly I"], "ingredients": ["Adhesive ×6", "Leather ×8", "Plastic ×2", "Purified Water ×1", "Cloth ×4"]}, {"name": "Strapped Water Bottle", "desc": "Increases the wearer's overall carry capacity by +60. Fresh water drink periodically.", "perks": ["Armorer III", "Strong Back I"], "ingredients": ["Adhesive ×5", "Leather ×6", "Plastic ×2", "Cloth ×4"]}], "dr": []}, "BPSquire": {"cc": [{"name": "Leather Frame", "desc": "Increases the wearer's overall carry capacity by +50. -2 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Sturdy Leather Frame", "desc": "Increases the wearer's overall carry capacity by +55. -1 Agility.", "perks": ["Armorer II", "Strong Back I"], "ingredients": ["Acid ×2", "Aluminum ×2", "Adhesive ×4", "Leather ×6", "Plastic ×2", "Cloth ×3"]}, {"name": "Supplementary Pocket", "desc": "Increases the wearer's overall carry capacity by +60.", "perks": ["Armorer III", "Strong Back II"], "ingredients": ["Acid ×4", "Adhesive ×4", "Leather ×4", "Plastic ×2", "Cloth ×3"]}, {"name": "Sturdy Pocketed Frame", "desc": "Increases the wearer's overall carry capacity by +60. +1 Endurance.", "perks": ["Armorer II", "Strong Back II"], "ingredients": ["Acid ×3", "Adhesive ×5", "Leather ×8", "Plastic ×4", "Cloth ×4"]}], "dr": [{"name": "Leather Shell", "desc": "Damage resistance +10.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Sturdy Leather Shell", "desc": "Damage resistance +20.", "perks": ["Armorer II"], "ingredients": ["Aluminum ×4", "Adhesive ×1", "Leather ×4", "Cloth ×2"]}, {"name": "Reinforced Leather Shell", "desc": "Damage resistance +30.", "perks": ["Armorer III"], "ingredients": ["Aluminum ×4", "Adhesive ×1", "Leather ×4", "Cloth ×2"]}]}, "BPMutant": {"cc": [{"name": "Wooden Trunk", "desc": "Increases the wearer's overall carry capacity by +50. -2 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Strapped Toolbox", "desc": "Increases the wearer's overall carry capacity by +55. -1 Agility. +1 Endurance. ", "perks": ["Armorer II", "Strong Back I"], "ingredients": ["Aluminum ×3", "Adhesive ×6", "Leather ×4", "Adjustable Wrench ×1"]}, {"name": "Extra Pouch", "desc": "Increases the wearer's overall carry capacity by +60. +1 Endurance. ", "perks": ["Armorer II", "Strong Back I"], "ingredients": ["Aluminum ×3", "Adhesive ×6", "Leather ×5", "Cloth ×10"]}, {"name": "Lucky Teddy Bear", "desc": "Increases the wearer's overall carry capacity by +65. +1 Endurance. +1 Luck.", "perks": ["Armorer II", "Strong Back II"], "ingredients": ["Adhesive ×7", "Leather ×5", "Teddy Bear ×1"]}, {"name": "Super Mutant's Strength", "desc": "Increases the wearer's overall carry capacity by +65. +1 Endurance. +25% unarmed damage.", "perks": ["Armorer II", "Strong Back II"], "ingredients": ["Adhesive ×7", "Leather ×5", "Teddy Bear ×1"]}], "dr": [{"name": "Trunk Shell", "desc": "Damage resistance +30.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Reinforced Trunk Shell", "desc": "Damage resistance +40.", "perks": ["Armorer II"], "ingredients": ["Aluminum ×10", "Adhesive ×4"]}]}, "BPRadio": {"cc": [{"name": "SRC-3000", "desc": "Increases the wearer's overall carry capacity by +50. -2 Agility. +5% Accuracy in VATS.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "SRC-3001", "desc": "Increases the wearer's overall carry capacity by +55. -1 Agility. +10% Accuracy in VATS.", "perks": ["Armorer I"], "ingredients": ["Circuitry ×2", "Copper ×5", "Fiberglass ×4", "Nuclear Material ×3"]}, {"name": "SRC-3002", "desc": "Increases the wearer's overall carry capacity by +60. +15% accuracy in VATS.", "perks": ["Armorer II", "Local Leader I"], "ingredients": ["Circuitry ×8", "Copper ×5", "Fiberglass ×3", "Nuclear Material ×7"]}, {"name": "SRC-3003", "desc": "Increases the wearer's overall carry capacity by +65. +20% accuracy in VATS.", "perks": ["Armorer III", "Local Leader II"], "ingredients": ["Circuitry ×9", "Copper ×8", "Fiberglass ×3", "Nuclear Material ×10"]}], "dr": []}, "BPStealth": {"cc": [{"name": "Electron Charged Coil", "desc": "Increases the wearer's overall carry capacity by +55. -1 Agility.", "perks": [], "ingredients": ["Aluminum ×2"]}, {"name": "Modulating Stealth Boy Mini-Field Generator", "desc": "Increases the wearer's overall carry capacity by +60. 10% harder to detect.", "perks": ["Armorer II", "Sneak I"], "ingredients": ["Aluminum ×6", "Crystal ×2", "Silver ×2", "Screw ×4", "Stealth Boy ×2"]}, {"name": "Third-Ion Plasma Reactor", "desc": "Increases the wearer's overall carry capacity by +65. +1 Endurance. +10 Rad Resist and +20 Energy Resist.", "perks": ["Armorer III", "Science! III"], "ingredients": ["Aluminum ×3", "Gold ×8", "Silver ×10", "Spring ×4", "Purified Water ×1", "Screw ×4"]}, {"name": "AutoDispense All-In-One Reactor", "desc": "Increases the wearer's overall carry capacity by +65. Water drink and rads removed periodically.", "perks": ["Armorer III", "Science! II"], "ingredients": ["Acid ×4", "Aluminum ×3", "Gold ×8", "Silver ×10", "Spring ×4", "RadAway ×1", "Screw ×4"]}, {"name": "Anti-Radioisotope Micro Generator", "desc": "Increases the wearer's overall carry capacity by +65. Removes rads periodically.", "perks": ["Armorer III", "Science! II"], "ingredients": ["Aluminum ×5", "Gold ×5", "Oil ×2", "Silver ×6", "Spring ×2", "Screw ×2"]}], "dr": []}, "BPNuka": {"cc": [{"name": "Nuka-Cola", "desc": "Increases the wearer's overall carry capacity by +60.", "perks": [], "ingredients": ["Nuka-Cola ×1"]}, {"name": "Nuka-Cola Victory", "desc": "Increases the wearer's overall carry capacity by +70. +2 Strength.", "perks": ["Chemist I"], "ingredients": ["Nuka-Cola ×4", "Nuka-Cola Victory ×4"]}, {"name": "Nuka-Cola Quartz", "desc": "Increases the wearer's overall carry capacity by +70. +2 Perception.", "perks": ["Chemist I"], "ingredients": ["Nuka-Cola ×4", "Nuka-Cola Quartz ×4"]}, {"name": "Nuka-Cola Grape", "desc": "Increases the wearer's overall carry capacity by +70. +2 Endurance.", "perks": ["Chemist I"], "ingredients": ["Nuka-Cola ×4", "Nuka-Grape ×2"]}, {"name": "Nuka-Cola Wild", "desc": "Increases the wearer's overall carry capacity by +70. +2 Luck.", "perks": ["Chemist I"], "ingredients": ["Nuka-Cola ×4", "Nuka-Cola Wild ×4"]}, {"name": "Nuka-Cola Rush", "desc": "Increases the wearer's overall carry capacity by +70. +2 Agility.", "perks": ["Chemist I"], "ingredients": ["Nuka-Cola ×4", "Nuka-Rush ×4"]}, {"name": "Nuka-Cola Quantum", "desc": "Increases the wearer's overall carry capacity by +65. +2 Intelligence.", "perks": ["Chemist I"], "ingredients": ["Nuka-Cola ×4", "Nuka-Cola Quantum ×6"]}, {"name": "Nuka-Lixir", "desc": "Increases the wearer's overall carry capacity by +70. +20 additional damage resistance and rad resistance.", "perks": ["Armorer II", "Chemist II"], "ingredients": ["Nuclear Material ×2", "Nuka-Cola ×4", "Nuka-Power ×3"]}, {"name": "Nuka-Power", "desc": "Increases the wearer's overall carry capacity by +100.", "perks": ["Armorer II", "Chemist II"], "ingredients": ["Nuclear Material ×2", "Nuka-Cola ×4", "Nuka-Power ×3"]}, {"name": "Nuka-Gold", "desc": "Increases the wearer's overall carry capacity by +110.", "perks": ["Armorer III", "Chemist II"], "ingredients": ["Nuclear Material ×2", "Nuka-Cola ×4", "Nuka-Gold ×2"]}, {"name": "Nuka-Cooler", "desc": "Increases the wearer's overall carry capacity by +70. +25 max HP and +10 max AP.", "perks": ["Chemist II", "Armorer I"], "ingredients": ["Nuclear Material ×2", "Nuka-Cola ×4", "Nuka-Cooler ×3"]}, {"name": "Nuka-Punch", "desc": "Increases the wearer's overall carry capacity by +70. Water drink regularly and rads removed periodically.", "perks": ["Armorer I", "Chemist II"], "ingredients": ["Nuclear Material ×2", "Nuka-Cola ×4", "Nuka-Punch ×3"]}], "dr": []}, "BPChem": {"cc": [{"name": "User's Collection", "desc": "Increases the wearer's overall carry capacity by +55. -2 Agility. +5% damage resistance per withdrawal effect.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Gateway Chem", "desc": "Increases the wearer's overall carry capacity by +60. -1 Agility. +5% damage resistance and +5% weapon damage per withdrawal effect.", "perks": ["Chemist II"], "ingredients": ["Adhesive ×4", "Stimpak ×1", "Med-X ×1", "Table Spoon ×1"]}, {"name": "Hidden Stash", "desc": "Increases the wearer's overall carry capacity by +65. +10% damage resistance and +5% weapon damage per withdrawal effect.", "perks": ["Chemist III"], "ingredients": ["Adhesive ×4", "Stimpak ×1", "Psycho ×1", "Table Spoon ×1"]}, {"name": "Intervention", "desc": "Increases the wearer's overall carry capacity by +70. +10% weapon damage and +10% damage resistance per withdrawal effect.", "perks": ["Chemist IV"], "ingredients": ["Adhesive ×4", "Stimpak ×1", "Med-X ×1", "Psycho ×1", "Table Spoon ×1"]}], "dr": []}, "BPScribe": {"cc": [{"name": "Leather Pouches", "desc": "Increases the wearer's overall carry capacity by +60. -2 Agility.", "perks": [], "ingredients": ["Leather ×2", "Cloth ×2"]}, {"name": "Sturdy Leather Pouches", "desc": "Increases the wearer's overall carry capacity by +65. -1 Agility.", "perks": ["Armorer II", "Strong Back I"], "ingredients": ["Adhesive ×5", "Leather ×6", "Plastic ×2", "Cloth ×6"]}, {"name": "Additional Front Pockets", "desc": "Increases the wearer's overall carry capacity by +70.", "perks": ["Armorer II", "Strong Back II"], "ingredients": ["Aluminum ×4", "Adhesive ×5", "Leather ×6", "Plastic ×4", "Cloth ×10"]}, {"name": "Front Pockets with Harness", "desc": "Increases the wearer's overall carry capacity by +75. +1 Endurance.", "perks": ["Armorer III", "Strong Back II"], "ingredients": ["Aluminum ×8", "Adhesive ×6", "Leather ×8", "Plastic ×4", "Cloth ×12"]}], "dr": []}, "BPMilitary": {"cc": [{"name": "Canvas Frame", "desc": "Increases the wearer's overall carry capacity by +70. -1 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Military Canvas Frame", "desc": "Increases the wearer's overall carry capacity by +75.", "perks": ["Armorer III", "Strong Back II"], "ingredients": ["Adhesive ×5", "Leather ×6", "Plastic ×2", "Cloth ×6"]}, {"name": "Military Ammo Harness", "desc": "Increases the wearer's overall carry capacity by +80. Weapon reload speed increased.", "perks": ["Armorer III", "Gun Nut III"], "ingredients": ["Aluminum ×6", "Adhesive ×5", "Leather ×8", "Plastic ×2"]}, {"name": "Military Ballistic Fiber Frame", "desc": "Increases the wearer's overall carry capacity by +80. +1 Endurance.", "perks": ["Armorer III", "Strong Back III"], "ingredients": ["Ballistic Fiber ×3", "Adhesive ×5", "Leather ×6", "Plastic ×2"]}], "dr": [{"name": "Canvas Shell", "desc": "Damage resistance +10.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Military Canvas Shell", "desc": "Damage resistance +30.", "perks": ["Armorer III"], "ingredients": ["Aluminum ×2", "Adhesive ×3", "Leather ×10", "Plastic ×2"]}]}, "BPBattery": {"cc": [{"name": "High-Powered Battery", "desc": "Increases the wearer's overall carry capacity by +80. -1 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Anti-Gravity Electromagnetic Field Generator", "desc": "Increases the wearer's overall carry capacity by +85. Generates anti-gravity field after jumping.", "perks": ["Rifleman II", "Science! III"], "ingredients": ["Aluminum ×5", "Fiber Optics ×2", "Gold ×5", "Nuclear Material ×10", "Oil ×2", "Screw ×4", "Fusion Core ×8", "High-Powered Magnet ×2"]}, {"name": "Electromagnetic Close Proximity Field Projectile Accelerator", "desc": "Increases the wearer's overall carry capacity by +85. +15% damage with ballistic guns.", "perks": ["Armorer II", "Science! IV"], "ingredients": ["Aluminum ×18", "Gold ×8", "Nuclear Material ×10", "Oil ×2", "Silver ×6", "Screw ×4", "Fusion Core ×8", "High-Powered Magnet ×3"]}], "dr": []}, "BPWoodsman": {"cc": [{"name": "Leather Frame", "desc": "Increases the wearer's overall carry capacity by +75. -2 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Reinforced Leather Frame", "desc": "Increases the wearer's overall carry capacity by +80. -1 Agility.", "perks": ["Armorer II"], "ingredients": ["Adhesive ×2", "Leather ×8", "Plastic ×6", "Cloth ×4"]}, {"name": "Water Canteen with RadAway First Aid Kit", "desc": "Increases the wearer's overall carry capacity by +85. Water drink regularly and rads removed periodically.", "perks": ["Medic II", "Lead Belly I"], "ingredients": ["Adhesive ×6", "Leather ×5", "RadAway ×1", "Purified Water ×1", "Cloth ×4"]}, {"name": "Knife Sharpening Sheath", "desc": "Increases the wearer's overall carry capacity by +85. Melee weapon damage increased by +10%.", "perks": ["Armorer III", "Big Leagues II"], "ingredients": ["Aluminum ×5", "Leather ×8", "Plastic ×4", "Combat Knife ×1", "Cloth ×4"]}, {"name": "Reinforced Shadowed Frame", "desc": "Increases the wearer's overall carry capacity by +90. Ranged sneak attacks do 1.5x normal damage.", "perks": ["Armorer III", "Ninja II"], "ingredients": ["Leather ×8", "Nuclear Material ×12", "Plastic ×4", "Stealth Boy ×1", "Cloth ×4"]}], "dr": []}, "BPMercenary": {"cc": [{"name": "Leather Frame", "desc": "Increases the wearer's overall carry capacity by +80. -1 Agility.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Military Leather Frame", "desc": "Increases the wearer's overall carry capacity by +85. +1 Endurance.", "perks": ["Armorer IV", "Strong Back III"], "ingredients": ["Adhesive ×8", "Leather ×10", "Screw ×7", "Cloth ×2"]}, {"name": "Military Ammunition Belt", "desc": "Increases the wearer's overall carry capacity by +85. +1 Endurance. Weapon reload speed increased.", "perks": ["Armorer IV", "Strong Back III"], "ingredients": ["Adhesive ×4", "Leather ×8", "Plastic ×2", "Cloth ×2"]}], "dr": [{"name": "Military Canvas Shell", "desc": "Damage resistance +10.", "perks": [], "ingredients": ["Adhesive ×1"]}, {"name": "Hardened Military Canvas Shell", "desc": "Damage resistance +20.", "perks": ["Armorer IV"], "ingredients": ["Adhesive ×5", "Leather ×6", "Plastic ×2", "Cloth ×6"]}]}, "BPVault": {"cc": [{"name": "Vault-Tec Standard Edition", "desc": "Increases the wearer's overall carry capacity by +90. -2 Agility.", "perks": [], "ingredients": ["Cloth ×1"]}, {"name": "Vault-Tec “Plenty-O'-Pockets” Edition", "desc": "Increases the wearer's overall carry capacity by +95.", "perks": ["Armorer II", "Science! II"], "ingredients": ["Adhesive ×8", "Gold ×12", "Lead ×8", "Nuclear Material ×10", "Cloth ×20"]}, {"name": "Vault-Tec “Goo-On-My-Shoe” Edition", "desc": "Increases the wearer's overall carry capacity by +100. +10% damage with energy weapons.", "perks": ["Armorer III", "Local Leader II"], "ingredients": ["Adhesive ×15", "Gold ×10", "Nuclear Material ×13", "Silver ×8", "Vault-Tec Utility Backpack Charisma Bobblehead ×1"]}, {"name": "Vault-Tec “Stealthy-Boy” Edition", "desc": "Increases the wearer's overall carry capacity by +100. 10% harder to detect.", "perks": ["Armorer III", "Gun Nut III"], "ingredients": ["Adhesive ×15", "Gold ×10", "Nuclear Material ×13", "Silver ×8", "Vault-Tec Utility Backpack Small Guns Bobblehead ×1"]}, {"name": "Vault-Tec “Big-Boom” Edition", "desc": "Increases the wearer's overall carry capacity by +100. +10% damage with ballistic guns.", "perks": ["Armorer III", "Sneak III"], "ingredients": ["Adhesive ×15", "Gold ×10", "Nuclear Material ×13", "Silver ×8", "Vault-Tec Utility Backpack Sneak Bobblehead ×1"]}, {"name": "Vault-Tec “Smooth-Operator” Edition", "desc": "Increases the wearer's overall carry capacity by +100. +1 Charisma.", "perks": ["Armorer III", "Science! III"], "ingredients": ["Adhesive ×15", "Gold ×10", "Nuclear Material ×13", "Silver ×8", "Vault-Tec Utility Backpack Energy Weapons Bobblehead ×1"]}], "dr": []}, "BPFusion": {"cc": [{"name": "Energy Cell Powered Coil", "desc": "Increases the wearer's overall carry capacity by +85. -2 Agility.", "perks": [], "ingredients": ["Aluminum ×1"]}, {"name": "Wattz Fission Battery", "desc": "Increases the wearer's carry capacity by +90. -1 Agility.", "perks": ["Armorer II", "Science! II"], "ingredients": ["Aluminum ×4", "Silver ×4", "Spring ×2", "Screw ×2"]}, {"name": "Poseidon Energy Plasma Accelerator", "desc": "Increases the wearer's overall carry capacity by +95.", "perks": ["Armorer III", "Science! III"], "ingredients": ["Aluminum ×3", "Gold ×2", "Silver ×2", "Spring ×4", "Screw ×4"]}, {"name": "TX-28 Microfusion Reactor", "desc": "Increases the wearer's overall carry capacity by +100. +1 Endurance.", "perks": ["Science! IV", "Strong Back II"], "ingredients": ["Aluminum ×5", "Glass ×2", "Gold ×8", "Nuclear Material ×6", "Plastic ×6", "Silver ×8", "RadAway ×1", "Purified Water ×1", "Fusion Core ×1", "Fusion Cell ×36"]}, {"name": "AutoDispense All-In-One Microfusion Reactor", "desc": "Increases the wearer's overall carry capacity by +100. Water drink regularly and rads removed periodically.", "perks": ["Strong Back II", "Science! IV"], "ingredients": ["Aluminum ×10", "Gold ×6", "Nuclear Material ×2", "Silver ×6", "Spring ×4", "Fusion Core ×1", "Fusion Cell ×12"]}, {"name": "AutoDispense TX-30 Microfusion Reactor", "desc": "Increases the wearer's overall carry capacity by +100. +1 Endurance. Water drink regularly and rads removed periodically.", "perks": ["Armorer III", "Science! IV"], "ingredients": ["Aluminum ×5", "Glass ×2", "Gold ×8", "Nuclear Material ×4", "Plastic ×6", "Silver ×5", "Spring ×5", "RadAway ×1", "Purified Water ×1", "Fusion Core ×1", "Fusion Cell ×24"]}], "dr": [{"name": "Ballistic Fiber Plating", "desc": "Damage resistance +30. Energy resistance +10. Rad resistance +10.", "perks": [], "ingredients": []}, {"name": "Ballistic Fiber and Titanium Carbide Plating", "desc": "Damage resistance +50. Energy resistance +20. Rad resistance +30.", "perks": ["Armorer IV", "Strong Back II"], "ingredients": ["Acid ×6", "Aluminum ×8", "Glass ×2", "Gold ×4", "Nuclear Material ×2", "Silver ×10", "Spring ×4"]}]}, "BPRobCo": {"cc": [{"name": "Standard Nukatility Frame", "desc": "Increases the wearer's overall carry capacity by +85. -1 Agility. Chills one Nuka-Cola or Nuka-Cherry to its Ice-Cold variant every six hours.", "perks": [], "ingredients": []}, {"name": "Reinforced Cooler Frame", "desc": "Increases the wearer's overall carry capacity by +90. Chills one Nuka-Cola or Nuka-Cherry to its Ice-Cold variant every four hours.", "perks": [], "ingredients": []}, {"name": "Quantum Thermoelectric Module", "desc": "Increases the wearer's overall carry capacity by +100. +15 Action Points. Chills one bottled Nuka-Cola of any flavor except Quantum to its Ice-Cold variant every three hours.", "perks": [], "ingredients": []}], "dr": [{"name": "Standard Lining", "desc": "Damage resistance +15. Rad resistance +10.", "perks": [], "ingredients": []}, {"name": "Insulated Lining", "desc": "Damage resistance +25. Energy resistance +10. Rad resistance +10.", "perks": [], "ingredients": []}, {"name": "Shielded Insulated Lining", "desc": "Damage resistance +30. Energy resistance +15. Rad resistance +30.", "perks": [], "ingredients": []}]}, "BPSentry": {"cc": [{"name": "S.E.N.T.R.Y. Field Relay", "desc": "Increases the wearer's overall carry capacity by +90. -2 Agility. Reconnaissance Burst outlines nearby enemies in red for 6 seconds during combat or while sneaking with a weapon drawn; 60-second recharge.", "perks": [], "ingredients": []}, {"name": "Reinforced Relay Chassis", "desc": "Increases the wearer's overall carry capacity by +95. -1 Agility. Reconnaissance Burst outlines nearby enemies in red for 6 seconds during combat or while sneaking with a weapon drawn; 60-second recharge.", "perks": [], "ingredients": []}, {"name": "Paladin Targeting Uplink", "desc": "Increases the wearer's overall carry capacity by +100. No Agility penalty. +10% VATS hit chance. Reconnaissance Burst outlines nearby enemies in red for 6 seconds during combat or while sneaking with a weapon drawn; 60-second recharge.", "perks": [], "ingredients": []}, {"name": "Powered Stabilization Harness", "desc": "Increases the wearer's overall carry capacity by +100. No Agility penalty. Reactive Aegis grants +75 DR/ER for 5 seconds at ≤35% health in combat; 60-second recharge. Reconnaissance Burst outlines nearby enemies in red for 6 seconds during combat or while sneaking with a weapon drawn; 60-second recharge.", "perks": [], "ingredients": []}], "dr": [{"name": "Standard Relay Plating", "desc": "Damage resistance +25. Energy resistance +15.", "perks": [], "ingredients": []}, {"name": "Reinforced Composite Plating", "desc": "Damage resistance +30. Energy resistance +20.", "perks": [], "ingredients": []}, {"name": "Paladin Shielded Plating", "desc": "Damage resistance +40. Energy resistance +35. Rad resistance +20.", "perks": [], "ingredients": []}]}, "BPArc": {"cc": [{"name": "Standard Capacitor Frame", "desc": "Increases the wearer's overall carry capacity by +100. No Agility penalty. Includes Capacitor Overload.", "perks": [], "ingredients": []}, {"name": "Reinforced Capacitor Frame", "desc": "Increases the wearer's overall carry capacity by +110. No Agility penalty. Includes Capacitor Overload.", "perks": [], "ingredients": []}], "dr": []}};

// Backpack thumbnails, in catalog order (one per record above).
const IMGS = [
  'assets/backpacks/01-small-shoulder-bag.webp',
  'assets/backpacks/02-postmans-mailbag.webp',
  'assets/backpacks/03-leather-shoulder-bag.webp',
  'assets/backpacks/04-raiders-harnessed-metal-container.webp',
  'assets/backpacks/05-outcasts-travel-pouch.webp',
  'assets/backpacks/06-makeshift-backpack.webp',
  'assets/backpacks/07-trappers-back-pouch.webp',
  'assets/backpacks/08-bedroll-backpack.webp',
  'assets/backpacks/09-military-duffle-bag.webp',
  'assets/backpacks/10-tinkers-rucksack.webp',
  'assets/backpacks/11-sling-pouch.webp',
  'assets/backpacks/12-mountaineers-backpack.webp',
  'assets/backpacks/13-wastelanders-backpack.webp',
  'assets/backpacks/14-squires-backpack.webp',
  'assets/backpacks/15-super-mutants-trunk.webp',
  'assets/backpacks/16-manpack-portable-radio-transceiver.webp',
  'assets/backpacks/17-r-o-b-b-personal-carrying-device-mk-i.webp',
  'assets/backpacks/18-limited-edition-nuka-pack.webp',
  'assets/backpacks/19-junkies-chem-stash.webp',
  'assets/backpacks/20-scribes-backpack.webp',
  'assets/backpacks/21-military-backpack.webp',
  'assets/backpacks/22-g-a-r-i-personal-carrying-device-mk-ii.webp',
  'assets/backpacks/23-woodsmans-backpack.webp',
  'assets/backpacks/24-mercenarys-rucksack.webp',
  'assets/backpacks/25-vault-tec-utility-backpack.webp',
  'assets/backpacks/26-p-e-g-a-fusion-powered-p-c-d-mk-iii.webp',
  'assets/backpacks/27-robco-nukatility-combo-pack.webp',
  'assets/backpacks/28-brotherhood-s-e-n-t-r-y-device.webp',
  'assets/backpacks/29-arc-tesla-p-c-d-mk-iv.webp'
];
